language : java
install :
    - cd core
    - ./compile-lib.sh
script :
    - ant
#    - cd ../tests && ant
    - cd ../examples/ && ant
    - java -cp bin/:../core/kraken.jar:../core/lib Example1
    - java -cp bin/:../core/kraken.jar:../core/lib Example2
    - java -cp bin/:../core/kraken.jar:../core/lib Example3
jdk : oraclejdk8
branches:
    only : master
notifications:
    slack: intech-sudparis:Z3xKQEmZT2a9BFBqouokQ6J7
    on_success: change
    on_failure: always
    email : false
