language : java
script :
    - cd core && ant
    - cd ../tests && ant
    - cd ../examples/example-1 && ant
    - java -cp bin/:../../core/kraken.jar Example1
jdk : oraclejdk8
branches:
    only : master
notifications:
    slack: intech-sudparis:Z3xKQEmZT2a9BFBqouokQ6J7
    on_success: change
    on_failure: always
